services:
  train:
    build: .
    restart: 'no'
    volumes:
      - ./models:/credit_card_fraud_detection/models
      - ./secrets/kaggle.json:/root/.config/kaggle/kaggle.json
    command: python src/main.py --train

  predict:
    build: .
    restart: 'no'
    volumes:
      - ./predictions/:/credit_card_fraud_detection/predictions
      - ./secrets/kaggle.json:/root/.config/kaggle/kaggle.json
    command: python src/main.py --predict